// Packing — pure game logic.
//
// Pack a set of rectangles into a fixed container with no gaps or overlaps.
// The pieces are generated by recursively guillotine-splitting the container,
// so they ALWAYS tile it exactly — the puzzle is therefore always solvable,
// and since the pieces' total area equals the container's, placing them all
// without overlap necessarily fills it. You win when every piece is placed.
//
// All exports are PURE FUNCTIONS. No React, no DOM.

export type Piece = {
  id: number
  w: number
  h: number
  /** Top-left position in the container, or null while in the tray. */
  x: number | null
  y: number | null
}

export type PackingState = {
  width: number
  height: number
  pieces: Piece[]
  moves: number
}

const W = 6
const H = 6

function makeRng(seed: number) {
  let rng = (seed || 1) | 0
  return () => {
    rng = (rng * 1103515245 + 12345) & 0x7fffffff
    return rng / 0x7fffffff
  }
}

/** Recursively guillotine-split a W×H rectangle into a set of sub-rectangles
 *  that exactly tile it. */
function splitTiling(rand: () => number): Array<{ x: number; y: number; w: number; h: number }> {
  const out: Array<{ x: number; y: number; w: number; h: number }> = []
  const rec = (x: number, y: number, w: number, h: number, depth: number) => {
    const canV = w >= 2
    const canH = h >= 2
    const smallEnough = w * h <= 6
    // Stop splitting: too deep, can't split, or randomly once reasonably small.
    if (depth >= 3 || (!canV && !canH) || (smallEnough && rand() < 0.5)) {
      out.push({ x, y, w, h })
      return
    }
    const vertical = canV && (!canH || rand() < 0.5)
    if (vertical) {
      const cut = 1 + Math.floor(rand() * (w - 1))
      rec(x, y, cut, h, depth + 1)
      rec(x + cut, y, w - cut, h, depth + 1)
    } else {
      const cut = 1 + Math.floor(rand() * (h - 1))
      rec(x, y, w, cut, depth + 1)
      rec(x, y + cut, w, h - cut, depth + 1)
    }
  }
  rec(0, 0, W, H, 0)
  return out
}

export function newGame(seed: number = Date.now()): PackingState {
  const rand = makeRng(seed)
  let rects = splitTiling(rand)
  // Want a fair puzzle: a handful of pieces, not one giant or 30 slivers.
  for (let attempt = 0; attempt < 20 && (rects.length < 4 || rects.length > 9); attempt++) {
    rects = splitTiling(rand)
  }
  const pieces: Piece[] = rects.map((r, i) => ({ id: i, w: r.w, h: r.h, x: null, y: null }))
  // Shuffle tray order so it isn't pre-sorted by the split.
  for (let i = pieces.length - 1; i > 0; i--) {
    const j = Math.floor(rand() * (i + 1))
    ;[pieces[i], pieces[j]] = [pieces[j], pieces[i]]
  }
  return { width: W, height: H, pieces, moves: 0 }
}

export function newPuzzle(): PackingState {
  return newGame()
}

export function getPiece(state: PackingState, id: number): Piece | undefined {
  return state.pieces.find(p => p.id === id)
}

/** Occupancy grid: cell value = piece id occupying it, or -1 if empty. */
export function occupancy(state: PackingState): number[][] {
  const grid = Array.from({ length: state.height }, () => new Array<number>(state.width).fill(-1))
  for (const p of state.pieces) {
    if (p.x === null || p.y === null) continue
    for (let r = 0; r < p.h; r++) {
      for (let c = 0; c < p.w; c++) {
        grid[p.y + r][p.x + c] = p.id
      }
    }
  }
  return grid
}

/** Can `piece` be placed with its top-left at (x,y)? In bounds and no overlap
 *  with any OTHER already-placed piece. */
export function canPlace(state: PackingState, piece: Piece, x: number, y: number): boolean {
  if (x < 0 || y < 0) return false
  if (x + piece.w > state.width || y + piece.h > state.height) return false
  const grid = occupancy(state)
  for (let r = 0; r < piece.h; r++) {
    for (let c = 0; c < piece.w; c++) {
      const occ = grid[y + r][x + c]
      if (occ !== -1 && occ !== piece.id) return false
    }
  }
  return true
}

export function place(state: PackingState, id: number, x: number, y: number): PackingState {
  const piece = getPiece(state, id)
  if (!piece) return state
  if (!canPlace(state, piece, x, y)) return state
  const pieces = state.pieces.map(p => (p.id === id ? { ...p, x, y } : p))
  return { ...state, pieces, moves: state.moves + 1 }
}

export function unplace(state: PackingState, id: number): PackingState {
  const piece = getPiece(state, id)
  if (!piece || piece.x === null) return state
  const pieces = state.pieces.map(p => (p.id === id ? { ...p, x: null, y: null } : p))
  return { ...state, pieces, moves: state.moves + 1 }
}

/** Every piece placed ⇒ the container is fully tiled (areas match, no overlap). */
export function isSolved(state: PackingState): boolean {
  return state.pieces.every(p => p.x !== null && p.y !== null)
}

export function placedCount(state: PackingState): number {
  return state.pieces.filter(p => p.x !== null).length
}

export function isLoss(_state: PackingState): boolean {
  return false
}
